configurable user collection
tugberkugurlu/AspNetCore.Identity.MongoDB pull request #27
Opened 2016-12-20 07:33 UTC by SorenZ

allow users to pass optional user's collection name to `MongoUserStore` constructor. #26

2016-12-20 12:04 UTC, tugberkugurlu commented on .gitignore
> +.vscode
This should not be ignored. This folder is from VS Code to hold workspace specific settings.

2016-12-20 12:06 UTC, tugberkugurlu commented on src/AspNetCore.Identity.MongoDB/MongoUserStore.cs
> +        public MongoUserStore(IMongoDatabase database, ILoggerFactory loggerFactory, string userCollectionName = "users")
Can you go with constructor overload instead of optional parameters? 

see http://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx/

2016-12-20 12:07 UTC, tugberkugurlu requested changes
@SorenZ Thanks for the PR 😄 Seems generally good, there are couple minor things to change. If you can change them, I will get this in 😄

2016-12-21 06:25 UTC, SorenZ commented on src/AspNetCore.Identity.MongoDB/MongoUserStore.cs
> +        public MongoUserStore(IMongoDatabase database, ILoggerFactory loggerFactory, string userCollectionName = "users")
of course, nice article :)

2016-12-21 08:06 UTC, SorenZ commented
@tugberkugurlu I hope the changes accepted. 
I learned nice things from your suggestions.
look forward to hear from you.

2016-12-21 16:52 UTC, tugberkugurlu approved these changes

2016-12-21 16:53 UTC, tugberkugurlu commented
@SorenZ great, thanks a lot! :shipit:

2016-12-21 16:53 UTC, merged